export const WEB_VIEW_PLATFORMS = {
  LUNA_IOS: 'LUNA_IOS',
  LUNA_ANDROID: 'LUNA_ANDROID',
  HYBRID_ANDROID: 'HYBRID_ANDROID',
  HYBRID_IOS: 'HYBRID_IOS',
  AURORA: 'AURORA',
} as const;

export const WEB_VIEW_ERROR_CODE = {
  FINGERPRINT_TIMEOUT_ERROR: 'FINGERPRINT_TIMEOUT_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  USER_INFO_ERROR: 'USER_INFO_ERROR',
} as const;

export const webviewResponseTimeout = 3000;
