/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";
import { webPushService } from "./webPushService";
import { readValue, saveValue } from "./helperDB";

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith("/_")) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.endsWith(".png"),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

const testPush = {
  data: {
    pushType: "unp_text",
    title: "",
    body: "awwawfwaw Вадим Б. приглашает вас в группу Близкие для получения дополнительных выгод в банке ВТБ https://sturdy-basket.surge.sh/about. Для Android - обновите ВТБ Онлайн https://vtb.ru/vtbonline",
    unp_sdk: "true",
    bellGroup: "main",
    deviceId: "05b8ce1a-b9ab-4dc6-bdd4-2941f6b36752",
    link: "https://sturdy-basket.surge.sh/?native=123",
    UnP__enrichedData: ' {"link":"https://vk.com/pettaysergey" } ',
    pushId: "d46d1776-8eda-462b-8c7c-cf710b3d5c25",
  },
  from: "507996965485",
  priority: "normal",
  fcmMessageId: "f1798ab2-7158-46b9-8f03-fd1b13e7edb5",
};

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }

  if (event.data.type === "SW:SendInApp") {
    const dataPush = testPush;
    const title = dataPush?.data.title || "";
    const message = dataPush?.data.body || "";

    event.waitUntil(
      readValue("myVar").then((res) => console.log("RES: ", res))
    );

    self.registration.showNotification(title, {
      lang: "ru-RU",
      body: message,
      data: dataPush.data,
      icon: "https://tvi.agency/static/img/clients/client-1.png",
    });
  }

  if (event.data.type === "SW:SendUnpUrl") {
    console.log("3: ", event.data);
    event.waitUntil(saveValue("myVar", event.data.payload));
  }
});

export type UnpPushData = {
  pushType: string;
  title: string;
  body: string;
  unp_sdk: string;
  bellGroup: string;
  deviceId: string;
  link: string;
  UnP__enrichedData: string;
  pushId: string;
};

export type UnpPush = {
  data: UnpPushData;
  from: string;
  priority: string;
  fcmMessageId: string;
};

const getOriginLink = (link: string, selfHost: string) => {
  const initialLink = new URL(link);
  const { host } = initialLink;
  // если ссылка ведет на любой из контуров ИБ (online.vtb.ru, online-alpha.vtb.ru, online.if.test.vtb.ru)
  if (host.includes(".vtb.ru")) {
    // в ссылке может придти не текущий хост (как пример: для пользователя на альфе придет ссылка на прод)
    initialLink.host = selfHost;

    return initialLink.toString();
  }

  return link;
};

self.addEventListener("push", (event) => {
  try {
    const dataPush = (event.data?.json() as UnpPush) ?? {};
    const title = dataPush?.data.title || "";
    const message = dataPush?.data.body || "";

    event.waitUntil(
      self
        .fetch("https://jsonplaceholder.typicode.com/posts/1")
        .then((response) => response.json())
        .then((json) => {
          console.log("JSON: ", json);

          self.registration.showNotification(json.title, {
            lang: "ru-RU",
            body: message,
          });
        })
    );
  } catch (error) {
    return;
  }
});

self.addEventListener("notificationclick", (e) => {
  e.preventDefault();
  e.notification.close();
  const { UnP__enrichedData, link } = e.notification.data as UnpPushData;

  const defaultTarget = link
    ? getOriginLink(link, self.location.host)
    : `${self.location.origin}/notifications`;

  const getTarget = () => {
    if (UnP__enrichedData) {
      try {
        const extendedInfo = JSON.parse(UnP__enrichedData)["extendedInfo"];

        if (extendedInfo && extendedInfo.link) {
          return getOriginLink(extendedInfo.link, self.location.host);
        }

        return defaultTarget;
      } catch (error) {
        return defaultTarget;
      }
    }

    return defaultTarget;
  };

  const target = getTarget();

  e.waitUntil(
    self.clients
      .matchAll({
        type: "window",
        includeUncontrolled: true,
      })
      .then((clientList) => {
        for (let i = 0; i < clientList.length; i++) {
          let client = clientList[i];
          // если хост совпадает
          if (
            new URL(client.url).host === new URL(target).host &&
            client.focused
          ) {
            setTimeout(() => {
              webPushService.port.postMessage({
                type: "SW::Push 1",
                payload: target,
              });
            }, 5000);
            return client.navigate(target);
          }
        }
        setTimeout(() => {
          webPushService.port.postMessage({
            type: "SW::Push 2",
            payload: target,
          });
        }, 5000);
        return self.clients.openWindow(target);
      })
  );
});
